#!/bin/bash
set -e

echo Running ruff src
uv run ruff check --fix src
echo Running ruff tests
uv run ruff check --fix tests
echo Running ruff tools
uv run ruff check --fix tools
echo Running black src tests tools
uv run black src tests tools
echo Running isort src tests tools
uv run isort --profile black src tests tools
echo Running pyright src tests tools
uv run pyright src tests tools
echo Linting complete!
exit 0
