#!/bin/bash

set -e

# if not activate present, install it
if ! command -v activate &> /dev/null; then
    echo "activate could not be found, installing it"
    bash install
fi


echo "Running unittests"
uv run pytest -n auto tests/unit -v --durations=0
# finally run the integration tests one by one.
uv run pytest tests/integration -v --durations=0 -s