name: MacOS_Tests

on: [push]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install UV
      run: pip install uv

    - name: Install GCC
      run: |
        brew update
        brew install gcc
        echo "Creating gcc symlinks to use real GCC instead of Clang"
        GCC_VERSION=$(ls -1 /usr/local/bin/gcc-* | grep -o '[0-9]*$' | sort -n | tail -1)
        echo "Found GCC version: $GCC_VERSION"
        mkdir -p $HOME/gcc-bin
        ln -sf /usr/local/bin/gcc-$GCC_VERSION $HOME/gcc-bin/gcc
        ln -sf /usr/local/bin/g++-$GCC_VERSION $HOME/gcc-bin/g++
        echo "PATH=$HOME/gcc-bin:$PATH" >> $GITHUB_ENV
        echo "CC=$HOME/gcc-bin/gcc" >> $GITHUB_ENV
        echo "CXX=$HOME/gcc-bin/g++" >> $GITHUB_ENV
        echo "Using GCC from: $HOME/gcc-bin/gcc"

    - name: Check compiler
      run: |
        which gcc
        gcc --version
        echo "CC=$CC"
        echo "CXX=$CXX"

    - name: Install
      run: ./install

    - name: Unit tests
      run: ./test
